length = int(input("Enter the length of the rectangle: "))
width = int(input("Enter the width of the rectangle: "))
area = float(length * width)
print(f"The area of the rectangle is: {area}")
perimeter = float(2 * (length + width))
print(f"The perimeter of the rectangle is: {perimeter}")